server:
    port: 8081
    servlet:
       context-path: /inventory
spring:
    datasource:
        url: jdbc:postgresql://localhost:5434/inventory-app-db
        username: inventory-app-db
        password: inventory-app-db
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    application:
        name: inventory-app